flask/matcha/views/chat.py
from flask import Blueprint, render_template, session, redirect, flash, request, url_for
from matcha.utils import login_required, complete_user_profile
from matcha import db

chatting = Blueprint('chat', __name__)

@chatting.route('/chat')
@login_required
@complete_user_profile
def chat():
    users = db.users()
    current_user = db.get_user({'username': session.get('username')}, {'matched': 1})
    return render_template('chat/chat.html', logged_in=session.get('username'), users=users, current_user=current_user)


@chatting.route('/room/<room>')
@login_required
@complete_user_profile
def chat_room(room):
    history = db.get_chat(room)
    chats = []
    username = ""
    
    if not history:
        db.create_history(room)
    else:
        for chat in history['chats']:
            value = (list(chat.values())[0])
            key = list(chat.keys())[0]
            data = list([key, value])
            if key != session.get('username'):
                print("Pass", key)
                # username = key
            chats.append(data)
        # user1 = db.get_user({'username': session.get('username')})
        # user2 = db.get_user({'username': username})
    # print("user1: ", user1['username'])
    print("Debug: ", chats)

    return render_template('chat/room.html', logged_in=session.get('username'), history=chats, room=room)

flask/matcha/views/profile.py
from flask import Blueprint, render_template, session, redirect, flash, request, url_for
from functools import wraps
import os, secrets, re, html, pymongo, bcrypt
from PIL import Image
from matcha import db, app, logged_in_users
from matcha.utils import save_image, save_image_to_gallery, login_required, complete_user_profile
from bson.objectid import ObjectId

from datetime import date
from bson import ObjectId

user = Blueprint("profile", __name__)


@user.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    user = db.get_user({"username": session.get("username")})

    errors = []
    location = []
    blocked = user["blocked"]
    users = db.users({"_id": {"$nin": blocked}, "completed": 1})

    if request.method == "POST":
        if request.form.get("submit") == "update":
            username = html.escape(request.form.get("username"))
            email = html.escape(request.form.get("email"))
            firstname = html.escape(request.form.get("firstname"))
            lastname = html.escape(request.form.get("lastname"))
            image = request.files.get("image")

            if not re.match("^[A-Za-z][A-Za-z0-9]{2,49}$", username):
                errors.append(
                    "The username must be an alpha numeric value, 3 - 50 characters long."
                )
            elif user["username"] != username and db.get_user({"username": username}):
                errors.append("The username is already taken please choose another")
            else:
                user["username"] = username
                session["username"] = username

            if not re.match(
                r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,100}$", email
            ):
                errors.append("invalid email format")
            elif user["email"] != email and db.get_user({"email": email}):
                errors.append("The email is already taken please choose another one")
            else:
                user["email"] = email
            if not firstname:
                errors.append("Firstname may not be empty")
            elif not re.match("^[A-Z][A-Za-z-]{2,24}$", firstname):
                errors.append(
                    "Firstname must begin with a capital letter and contain only: letters and/or -'s"
                )
            else:
                user["firstname"] = firstname

            if not lastname:
                errors.append("Lastname may not be empty")
            elif not re.match("^[A-Z][ A-Za-z-]{2,24}$", lastname):
                errors.append(
                    "Lastname must begin with a capital letter and contain only: letters, spaces and/or -'s"
                )
            else:
                user["lastname"] = lastname

            if image:
                pic_name = save_image(image)
                user["image_name"] = pic_name

            if not errors:
                db.update_user(user["_id"], user)
                flash("User user_info updated", "success")
                return redirect(url_for("profile.profile"))

            for error in errors:
                flash(error, "danger")

        if request.form.get("submitPwd") == "update":
            password = html.escape(request.form.get("current_password"))
            new_password = html.escape(request.form.get("new_password"))
            check_new_password = html.escape(request.form.get("new_password_repeat"))
            if not bcrypt.checkpw(password.encode("utf-8"), user["password"]):
                errors.append("Incorrect password")
            elif new_password:
                if not re.match(r'^.*(?=.{8,10})(?=.*[a-zA-Z])(?=.*?[A-Z])(?=.*\d)[a-zA-Z0-9!@£$%^&*()_+={}?:~\[\]]+$', new_password):
                    errors.append('The password must have an uppercase, lowercase and a digit')
                if check_new_password != new_password:
                    errors.append("The two passwords do not match")
                else:
                    salt = bcrypt.gensalt()
                    user["password"] = bcrypt.hashpw(new_password.encode("utf-8"), salt)
                    db.update_user(user["_id"], user)

            if not errors:
                db.update_user(user["_id"], user)
                flash("Password updated", "success")
            else:
                for error in errors:
                    flash(error, "danger")

        if request.form.get("submit") == "bioupdate":
            gender = request.form.get("gender")
            sexuality = request.form.get("sexo")
            interests = request.form.getlist("interests")
            bio = html.escape(request.form.get("bio"))
            image = request.files.get("image2")
            if not interests:
                interests = ["none"]
            if not bio:
                errors.append("Bio may not be empty")
            elif len(bio) > 500:
                errors.append("The Bio may not be longer than 500 characters")
            else:
                user["bio"] = bio

            if image:
                pic_name = save_image(image)
                user["image_name"] = pic_name

            elif user["image_name"] == "default.png":
                errors.append("Please update your photo.")

            if not errors:
                user["gender"] = gender
                user["sexual_orientation"] = sexuality
                user["interests"] = interests
                user["completed"] = 1
                location = request.form.get("location")
                location = location.split(",")
                lat = location.pop(3)
                lon = location.pop(3)
                user["location"] = location
                user["latlon"] = [lat, lon]
                db.update_user(user["_id"], user)
                flash("Profile updated", "success")
                return redirect(url_for("profile.profile"))

            for error in errors:
                flash(error, "danger")

        if request.form.get("submit") == "Upload":
            image_count = len(user["gallery"])
            if image_count < 4:
                image = request.files.get("image3")
                if image:
                    gallery_img = save_image_to_gallery(image)
                    user["gallery"].append(gallery_img)

                    db.update_user(user["_id"], user)
                    return redirect(url_for("profile.profile"))
            else:
                flash("You can only have 4 pictures in your gallery", "danger")

    bio = html.unescape(user['bio'])
    user['bio'] = bio
    viewers = []
    for id in user["views"]:
        viewers.append(db.get_user({"_id": ObjectId(id)}))

    likes = []
    for username in user["liked"]:
        likes.append(db.get_user({"username": username}))

    matched = []
    for username in user["matched"]:
        matched.append(db.get_user({"username": username}))


    blocked = []
    for user_id in user['blocked']:
        blocked.append(db.get_user({"_id": user_id}))

    online_users = list(logged_in_users.keys())
    return render_template(
        "user/profile.html",
        logged_in=session.get('username'),
        current_user=user,
        online_users=online_users,
        viewers=viewers,
        likes=likes,
        matched=matched,
        blocked=blocked
    )


@user.route("/profile/view/<user_id>")
@login_required
@complete_user_profile
def view_profile(user_id):
    id = ObjectId(user_id)
    current_user = db.get_user({"username": session.get("username")})

    user = db.get_user({"_id": id})
    online_users = list(logged_in_users.keys())
    bio = html.unescape(user['bio'])
    user['bio'] = bio
    return render_template(
        "user/view_profile.html",
        logged_in=session.get('username'),
        user=user,
        online_users=online_users,
        current_user=current_user
    )


flask/matcha/templates/user/users.html
{% extends 'base.html' %} {% block content %}
<div class="section">
  <div class="btn-group">
    <button
      type="button"
      class="btn dropdown-toggle btn-sm"
      data-toggle="dropdown"
      aria-haspopup="true"
      aria-expanded="false"
      id="fame"
    >
      Fame
    </button>
    <div class="dropdown-menu">
      <a
        class="dropdown-item"
        href="{{ url_for('main.sort_fame', value='Sort_d') }}"
        >sort by descending</a
      >
      <a
        class="dropdown-item"
        href="{{ url_for('main.sort_fame', value='Sort_a') }}"
        >sort by ascending</a
      >
    </div>
  </div>
  <div class="btn-group">
    <button
      type="button"
      class="btn dropdown-toggle btn-sm"
      data-toggle="dropdown"
      aria-haspopup="true"
      aria-expanded="false"
      id="fame"
    >
      Age
    </button>
    <div class="dropdown-menu">
      <a
        class="dropdown-item"
        href="{{ url_for('main.sort_age', value='Sort_d') }}"
        >sort by descending</a
      >
      <a
        class="dropdown-item"
        href="{{ url_for('main.sort_age', value='Sort_a') }}"
        >sort by ascending</a
      >
    </div>
  </div>

  <div class="btn-group">
  </div>

  <div class="btn-group"></div>
</div>

<div class="content-sections">
  {% for user in users %} {% if logged_in != user['username'] %}
  <h3>
    <a class="mr-2" href="{{ url_for('profile.view_profile', user_id=user['_id'])}}">{{ user['username'] }}</a>
  </h3>
  <article class="media content-section">
    <img
      class="article-img rounded"
      src="{{ url_for('static', filename='profile_pics/' + user['image_name']) }}"
      alt="Profile Pic"
    />
    <div class="media-body">
      <div class="article-metadata border-bottom">
        <small class="text-muted"
          >Fame: {{user['fame-rating']}}% Age: {{ user['age'] }} Location: {{
          user['location'][2]}}</small
        >
        {% if logged_in in user['liked'] %}
        <div>
          {% if user['username'] in current_user['liked'] %}
          <a
            href="{{ url_for('chat.chat_room', room=user['rooms'][logged_in]) }}"
            class="btn btn btn-outline-info"
            >Chat</a
          >
          {% else %}
          <a href="#" class="pending btn"
            >Pending</a
          >
          {% endif %}
          <button
            type="button"
            class="unlike btn"
            value="{{ user['username'] }}"
          >
            unlike
          </button>
        </div>
        {% else %}
        <div>
          {% if user['username'] in current_user['liked'] %}
          <button
            type="button"
            value="{{ user['username'] }}"
            class="like-back btn"
          >
            Like Back
          </button>
          {% else%}
          <button
            type="button"
            value='{{ user["username"] }}'
            class="like btn"
          >
            Like
          </button>
          {% endif %}
        </div>
        {% endif %}
        <a
          href="{{ url_for('main.block_user', b_id=user['_id']) }}"
          class="btn"
          >Block</a
        >
      </div>
    </div>
  </article>
  {% endif %} {% endfor %}
</div>
{% endblock content %} {% block js %}
<script>
  socket = io("http://localhost:5000");
  var_name = $("#username").text();

  $(".like").each(function () {
    $(this).on("click", function (e) {
      socket.emit("like", {
        to: $(this).val(),
      });
      $(this).removeClass("like");
      $(this).addClass("disabled");
      $(this).addClass("pending");
      $(this).text("pending");
      $(this).unbind("click", arguments.callee);
    });
  });

  $(".like-back").each(function () {
    $(this).on("click", function (e) {
      socket.emit("like-back", { to: $(this).val() });
      $(this).replaceWith(
        "<a href='#' class='btn btn-outline-info btn-sm sm-1 disabled'>Chat</a>"
      );
    });
  });

  $(".unlike").each(function () {
    $(this).on("click", function (e) {
      socket.emit("Unlike", { to: $(this).val() });
      window.location.reload();
    });
  });

  socket.on("like", function (data) {
    alert(data["from"]);

    $(".like").each(function () {
      if ($(this).val() == data["from"]) {
        window.location.reload();
      }
    });
  });

  socket.on("matched", function (data) {
    $(".pending").each(function () {
      if ($(this).val() == data["from"]) {
        $(this).replaceWith(
          "<a href='#' class='btn btn-outline-info btn-sm sm-1 disabled'>Chat</a>"
        );
      }
    });
  });

  socket.on("Unlike", function (data) {
    $(".like-back").each(function () {
      if ($(this).val() == data["from"]) {
        window.location.reload();
      }
    });
  });

  socket.on("notif_chat", function (data) {
    $("notification").append("<p>" + data["from"] + " sent you a message</p>");
    $("#badge").text("new");
  });

  socket.on("notif_view", function (data) {
    $("#notification").append(
      "<p>" + data["from"] + " viewed your profile</p>"
    );
    $("#badge").text("new");
  });

  $("#inbox").on("click", function () {
    socket.emit("read", { user: $("#username").text() });
    $("#badge").text("");
  });
</script>
<script>
  let traveling = "";
  let animals = "";
  let technology = "";
  let skyDiving = "";
  let movies = "";
  let music = "";
  let cooking = "";
  let sports = "";
  let gaming = "";

  const interests = [];

  document.getElementById('traveling').addEventListener("click", function (e) {
    traveling = e.target.value;
    interests.push(traveling);
  });
  document.getElementById('animals').addEventListener("click", function (e) {
    animals = e.target.value;
    interests.push(animals);
  });
  document.getElementById('technology').addEventListener("click", function (e) {
    technology = e.target.value;
    interests.push(technology);
  });
  document.getElementById('sky-diving').addEventListener("click", function (e) {
    skyDiving = e.target.value;
    interests.push(skyDiving);
  });
  document.getElementById('movies').addEventListener("click", function (e) {
    movies = e.target.value;
    interests.push(movies);
  });
  document.getElementById('music').addEventListener("click", function (e) {
    music = e.target.value;
    interests.push(music);
  });
  document.getElementById('cooking').addEventListener("click", function (e) {
    cooking = e.target.value;
    interests.push(cooking);
  });
  document.getElementById('sports').addEventListener("click", function (e) {
    sports = e.target.value;
    interests.push(sports);
  });
  document.getElementById('gaming').addEventListener("click", function (e) {
    gaming = e.target.value;
    interests.push(gaming);
  });

  function advance_search() {
    const age = document.getElementById('age').value;
    const fame = document.getElementById('fame1').value;
    const location = document.getElementById('location').value;
    fetch("http://localhost:5000/users/advance_search/search",
      {
        method: 'POST',
        mode: "cors",
        cache: "no-cache",
        credentials: "same-origin",
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ "Age": age, "Fame": fame, "Location": location, "Interests": interests })
      }
    );
  }
</script>
{% endblock js %}

flask/matcha/templates/user/view_profile.html
{% extends 'base.html' %} {% block content %}
<p hidden id='user_id'>{{ user['_id'] }}</p>
<p hidden id='current_user_id'>{{ current_user['_id'] }}</p>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            {% if logged_in in user['liked'] %}
                {% if user['username'] in current_user['liked'] %}
        <a href="{{ url_for('chat.chat_room', room=user['rooms'][logged_in]) }}"
            class='btn btn-outline-info btn-sm m-1'>Chat</a>
                {% else %}
                <a href="#" class='pending btn btn-outline-info disabled'>Pending</a>
                {% endif %}
                <button type='button' class='unlike btn btn-outline-info' value="{{ user['username'] }}">unlike</button>
            {% else %}
                {% if user['username'] in current_user['liked'] %}
                <button type='button' value="{{ user['username'] }}" class='like-back btn btn-outline-info'>Like
                    Back</button>
                {% else%}
                <button type='button' value='{{ user["username"] }}' class='like btn btn-outline-info'>Like</button>
                {% endif %}
            {% endif %}
            <a href="{{ url_for('main.block_user', b_id=user['_id']) }}" class='btn btn-outline-info'>Block</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="media">
                <img src="{{ url_for('static', filename='profile_pics/' + user['image_name'])}}" alt="profile"
                    class="rounded-circle account-img">
                <div class="media-body">
                    <h6 class='text-muted text-secondary'>Username: </h6>
                    <p>{{ user['username'] }}</p>
                    <h6 class='text-muted text-secondary'>First Name: </h6>
                    <p>{{ user['firstname'] }}</p>
                    <h6 class='text-muted text-secondary'>Last Name: </h6>
                    <p>{{ user['lastname'] }}</p>
                    <h6 class="text-muted text-secondary">Gender: </h6>
                    <p>{{ user['gender'] }}</p>
                    <h6 class="text-muted text-secondary">Sexual Orientation: </h6>
                    <p>{{ user['sexual_orientation'] }}</p>
                    <h6 class="text-muted text-secondary">Age: </h6>
                    <p>{{ user['age'] }}</p>
                    <h6 class='text-muted text-primary'>Bio:</h6>
                    <p>{{user['bio']}}</p>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <h6 class="text-muted text-secondary">Location: </h6>
            <p>{{ user['location'][2]}}</p>
            <h6 class="text-muted text-secondary">Fame Rating: </h6>
            <p>{{ user['fame-rating']}}%</p>
            <h6 class="text-muted text-secondary">Status: </h6>
            {% if user['username'] in online_users %}
                <p class='text-muted text-primary'>Online</p>
            {% else %}
                <p class='text-muted text-secondary'>Last seen: {{ user['last-seen'].strftime("%H:%M %Y-%m-%d") }}</p>
            {% endif%}
            <h6 class='text-muted text-primary'>Interests:</h6>
            {% for interest in user['interests']%}
                <p>{{interest}}</p>
            {%endfor%}
        </div>
    </div>
    {% if current_user['gallery'] is defined %}
    <div class="row">
        <div class="col-sm-12">
                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel"
                    style="width: 250px; height:150px; margin: 0 auto">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img style="width: 100%; border: solid 2px black; box-shadow: 5px 9px 10px #888888" height="150px"
                                width="250px"
                                src="{{ url_for('static', filename='gallery_pics/' + user['gallery'][0])}}" alt="slide">
                        </div>
                        <div class="carousel-item">
                            <img style="width: 100%; border: solid 2px black; box-shadow: 5px 9px 10px #888888" height="150px"
                                width="250px"
                                src="{{ url_for('static', filename='gallery_pics/' + user['gallery'][1])}}" alt="slide">
                        </div>
                        <div class="carousel-item">
                            <img style="width: 100%; border: solid 2px black; box-shadow: 5px 9px 10px #888888" height="150px"
                                width="250px"
                                src="{{ url_for('static', filename='gallery_pics/' + user['gallery'][2])}}" alt="slide">
                        </div>
                        <div class="carousel-item">
                            <img style="width: 100%; border: solid 2px lightcoral; box-shadow: 5px 9px 10px burlywood" height="150px"
                                width="250px"
                                src="{{ url_for('static', filename='gallery_pics/' + user['gallery'][3])}}" alt="slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
    {%endif%}
</div>
{% endblock content %}
{% block js %}
<script>
    socket = io('http://localhost:5000');

    $(document).ready(function(){
        socket.emit('view', {'viewer': $('#current_user_id').text(), 'viewed': $('#user_id').text()});
    });

      $('.like').each(function () {
            $(this).on('click', function (e) {
                socket.emit('like', {
                    'to': $(this).val()
                });
                $(this).removeClass('like');
                $(this).addClass('disabled');
                $(this).addClass('pending')
                $(this).text('pending');
                $(this).unbind('click', arguments.callee);
            });
        });

        $('.like-back').each(function () {
            $(this).on('click', function (e) {
                socket.emit('like-back', { 'to': $(this).val() });
                $(this).replaceWith("<a href='#' class='btn btn-outline-info btn-sm sm-1 disabled'>Chat</a>");
            });
        });

        $('.unlike').each(function () {
            $(this).on('click', function (e) {
                socket.emit('Unlike', { 'to': $(this).val() });
                window.location.reload();
            });
        });
        socket.on('like', function (data) {
            $('.like').each(function () {
                if ($(this).val() == data['from']) {
                    window.location.reload();
                }
            });

        });

        socket.on('matched', function (data) {
            $('.pending').each(function () {
                if ($(this).val() == data['from']) {
                    $(this).replaceWith("<a href='#' class='btn btn-outline-info btn-sm sm-1 disabled'>Chat</a>");
                }
            });
        });

        socket.on('Unlike', function (data) {
            $('.like-back').each(function () {
                if ($(this).val() == data['from']) {
                    window.location.reload()
                }
            });
        });


        socket.on('notif_chat', function (data) {
            $('notification').append('<p>' + data['from'] + ' sent you a message</p>');
            $('#badge').text('new');
        });

        socket.on('notif_view', function (data) {
            $('#notification').append('<p>' + data['from'] + ' viewed your profile</p>');
            $('#badge').text('new');
        });

        $('#inbox').on('click', function () {
            socket.emit('read', { "user": $('#username').text() });
            $('#badge').text('');
        });
</script>
{% endblock js %}