flask/matcha/views/chat.py
from flask import Blueprint, render_template, session, redirect, flash, request, url_for
from matcha.utils import login_required, complete_user_profile
from matcha import db

chatting = Blueprint('chat', __name__)

@chatting.route('/chat')
@login_required
@complete_user_profile
def chat():
    users = db.users()
    current_user = db.get_user({'username': session.get('username')}, {'matched': 1})
    return render_template('chat/chat.html', logged_in=session.get('username'), users=users, current_user=current_user)


@chatting.route('/room/<room>')
@login_required
@complete_user_profile
def chat_room(room):
    history = db.get_chat(room)
    chats = []
    username = ""
    
    if not history:
        db.create_history(room)
    else:
        for chat in history['chats']:
            value = (list(chat.values())[0])
            key = list(chat.keys())[0]
            data = list([key, value])
            if key != session.get('username'):
                print("Pass", key)
                # username = key
            chats.append(data)
        # user1 = db.get_user({'username': session.get('username')})
        # user2 = db.get_user({'username': username})
    # print("user1: ", user1['username'])
    print("Debug: ", chats)

    return render_template('chat/room.html', logged_in=session.get('username'), history=chats, room=room)

flask/matcha/views/home.py
from matcha import db, logged_in_users, filter_users
from flask import Blueprint, render_template, session, redirect, flash, request, url_for
from bson.objectid import ObjectId
from functools import wraps, cmp_to_key
from matcha.utils import common_interest, \
filter_age, filter_interest, filter_location, login_required, \
complete_user_profile, filter_fame

main = Blueprint("main", __name__)

# Create the route for the home page
@main.route("/")
@login_required
@complete_user_profile
def home():
    user = db.get_user({"username": session.get("username")}, {"notifications": 1})
    return render_template(
        "home.html", logged_in=session.get("username"), current_user=user
    )


@main.route("/users")
@login_required
@complete_user_profile
def users():
    current_user = db.get_user({"username": session.get("username")})
    blocked = current_user["blocked"]
    opp_gen = "Male" if current_user["gender"] == "Female" else "Female"
    gen = current_user["gender"]

    if current_user["sexual_orientation"] == "heterosexual":
        users = list(
            db.users(
                {
                    "_id": {"$nin": blocked},
                    "gender": opp_gen,
                    "sexual_orientation": {"$nin": ["homosexual"]},
                }
            )
        )
    elif current_user["sexual_orientation"] == "homosexual":
        users = list(
            db.users(
                {
                    "_id": {"$nin": blocked},
                    "gender": gen,
                    "sexual_orientation": {"$nin": ["heterosexual"]},
                }
            )
        )
    else:
        users = list(
            db.users(
                {
                    "$and": [
                        {"_id": {"$nin": blocked}},
                        {
                            "$or": [
                                {"sexual_orientation": "bisexual"},
                                {
                                    "$or": [
                                        {
                                            "$and": [
                                                {"sexual_orientation": "homosexual"},
                                                {"gender": gen},
                                            ]
                                        },
                                        {
                                            "$and": [
                                                {"sexual_orientation": "heterosexual"},
                                                {"gender": opp_gen},
                                            ]
                                        },
                                    ]
                                },
                            ]
                        },
                    ]
                }
            )
        )

    global filter_users
    filter_users = [
        user
        for user in users
        if user["username"] != current_user["username"]
        and common_interest(current_user["interests"], user["interests"]) >= 0
        and user["completed"] == 1
        and user['location'][2] == current_user['location'][2]
        and user['fame-rating'] >= 50
    ]

    return render_template(
        "user/users.html",
        logged_in=session.get("username"),
        users=filter_users,
        current_user=current_user,
        search=True,
    )


@main.route("/users/search_age/search", methods=["GET", "POST"])
@login_required
@complete_user_profile
def search_age():
    global filter_users
    if request.method == "POST":
        age = request.form.get("age")

        if not age.isnumeric():
            flash("invalid input for age search", "danger")
            return redirect(url_for("main.users"))
        current_user = db.get_user({"username": session.get("username")})
        blocked = current_user["blocked"]
        users = db.users({"_id": {"$nin": blocked}, "gender": {"$ne": current_user['gender']}, "completed": 1})
        age = int((age.replace(" ", "")).split(",")[0])
        filter_users = filter_age(users, age)

        return render_template(
            "user/users.html",
            logged_in=session.get("username"),
            users=filter_users,
            current_user=current_user,
            search=True,
        )

    return redirect(url_for("main.users"))

@main.route("/users/search_fame/search", methods=["GET", "POST"])
@login_required
@complete_user_profile
def search_fame():
    global filter_users
    if request.method == "POST":
        print("Debug 1", request.form.get("fame"))
        fame = request.form.get("fame")

        if not fame.isnumeric():
            flash("invalid input for age search", "danger")
            return redirect(url_for("main.users"))
        current_user = db.get_user({"username": session.get("username")})
        blocked = current_user["blocked"]
        users = db.users({"_id": {"$nin": blocked}, "gender": {"$ne": current_user['gender']}, "completed": 1})
        fame = int((fame.replace(" ", "")).split(",")[0])
        filter_users = filter_fame(users, fame)

        return render_template(
            "user/users.html",
            logged_in=session.get("username"),
            users=filter_users,
            current_user=current_user,
            search=True,
        )

    return redirect(url_for("main.users"))


@main.route("/users/interest/search", methods=["GET", "POST"])
@login_required
@complete_user_profile
def search_interest():
    global filter_users

    if request.method == "POST":
        interest = []
        if request.form.get("Traveling"):
            interest.append(request.form.get("Traveling"))
        if request.form.get("Animals"):
            interest.append(request.form.get("Animals"))
        if request.form.get("Technology"):
            interest.append(request.form.get("Technology"))
        if request.form.get("Sky-diving"):
            interest.append(request.form.get("Sky-diving"))
        if request.form.get("Movies"):
            interest.append(request.form.get("Movies"))
        if request.form.get("Music"):
            interest.append(request.form.get("Music"))
        if request.form.get("Cooking"):
            interest.append(request.form.get("Cooking"))
        if request.form.get("Sports"):
            interest.append(request.form.get("Sports"))
        if request.form.get("Gaming"):
            interest.append(request.form.get("Gaming"))

        current_user = db.get_user({"username": session.get("username")})
        blocked = current_user["blocked"]
        users = db.users({"_id": {"$nin": blocked}, "gender": {"$ne": current_user['gender']}, "completed": 1})
        filter_users = filter_interest(users, interest)

        return render_template(
            "user/users.html",
            logged_in=session.get("username"),
            users=filter_users,
            current_user=current_user,
            search=True,
        )

    return redirect(url_for("main.users"))


@main.route("/users/location/search", methods=["GET", "POST"])
@login_required
@complete_user_profile
def search_location():
    global filter_users
    print("Debug location ", request.form.get("location"))
    if request.method == "POST":
        location = request.form.get("location")
        current_user = db.get_user({"username": session.get("username")})
        blocked = current_user["blocked"]
        users = db.users({"_id": {"$nin": blocked}, "completed": 1})
        filter_users = filter_location(users, location)

        return render_template(
            "user/users.html",
            logged_in=session.get("username"),
            users=filter_users,
            current_user=current_user,
            search=True,
        )

    return redirect(url_for("main.users"))


@main.route("/users/username/search", methods=["GET", "POST"])
@login_required
@complete_user_profile
def search_username():
    global filter_users
    if request.method == "POST":
        username = request.form.get('username')
        print(username)
        current_user = db.get_user({'username' : session.get('username')})
        blocked = current_user["blocked"]
        filter_users = list(db.users({'_id' : { '$nin' : blocked }, 'completed' : 1, 'username': username}))

        return render_template(
            "user/users.html",
            logged_in=session.get("username"),
            users=filter_users,
            current_user=current_user,
            search=True,
        )

    return redirect(url_for("main.users"))


@main.route("/users/sort/fame/<value>", methods=["GET", "POST"])
@login_required
@complete_user_profile
def sort_fame(value):
    global filter_users
    current_user = db.get_user({"username": session.get("username")})

    if value == "Sort_d":
        sorted_users = filter_users[:]
        for i in range(len(sorted_users)):
            for k in range(len(sorted_users)):
                if sorted_users[i]["fame-rating"] > sorted_users[k]["fame-rating"]:
                    sorted_users[i], sorted_users[k] = sorted_users[k], sorted_users[i]
        [print(user["username"], user["fame-rating"]) for user in sorted_users]

        return render_template(
            "user/users.html",
            logged_in=session.get("username"),
            users=sorted_users,
            current_user=current_user,
            search=True,
        )
    if value == "Sort_a":
        sorted_users = filter_users[:]
        for i in range(len(sorted_users)):
            for k in range(len(sorted_users)):
                if sorted_users[i]["fame-rating"] < sorted_users[k]["fame-rating"]:
                    sorted_users[i], sorted_users[k] = sorted_users[k], sorted_users[i]

flask/matcha/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Might stop favicon.ico error in console.  -->
    <link rel="shortcut icon" href="../static/logos/favicon.ico">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Custom css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='../static/logos/logoblk.ico') }}" type="image/x-icon" />

    <title>Matcha</title>
</head>
<p id='username' class='d-none'> {{ logged_in }}</p>

<body>
    <header class="site-header">
        <nav style="background: rosybrown!important;"class="navbar d-print navbar-expand-md navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Matcha</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if logged_in %}
                        <a class="nav-item nav-link" href="{{  url_for('main.users') }}">Profiles</a>
                        <a href="{{ url_for('profile.profile') }}" class="nav-item nav-link">Profile</a>
                        <a href="{{ url_for('auth.logout') }}" class="nav-item nav-link">Logout</a>
                        <a href="{{ url_for('chat.chat')}}" class="nav-item nav-link">Chats</a>
                        <button type='button' id='inbox' class="notification btn" data-toggle="collapse" data-target="#notification" aria-expanded="false" aria-controls="collapse">
                            <span>Notifications</span>
                            {% if current_user and current_user['notifications'] %}
                            <span class="badge" id='badge'>new</span>
                            {% else %}
                            <span class="badge" id='badge'></span>
                            {% endif %}
                        </button> {% else %}
                        
                        <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a> {% endif %}
                    </div>

                </div>
            </div>
        </nav>
    </header>
    
    <div class="bannerbig"></div>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %} {% endif %} {% endwith %} {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    {% if current_user %}
                    <div class="collapse" id='notification'>
                        {% for notif in current_user['notifications'] %}
                        <p>{{ notif }}</p>
                        {% endfor %}
                    </div>
                    {% endif %} {% if search %}
                    <h3>Search</h3>
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light">
                                <form action="{{ url_for('main.search_username') }}" method='POST'>
                                    <input class="form-control" type="text" name='username' placeholder="username">
                                    <br />
                                    <input type="submit" name='submit' value='search' class='btn btn-sm btn-outline-info'>
                                </form>
                            </li>
                            <li class="list-group-item list-group-item-light">
                                Age
                                <form action="{{ url_for('main.search_age') }}" method='POST'>
                                    <select class="form-control" name="age" id="age">
                                        <option value="">Choose option</option>
                                        <option value="29">18 to 29</option>
                                        <option value="39">30 to 39</option>
                                        <option value="100">over 40</option>
                                    </select>
                                    <br />
                                    <input type="submit" name='submit' value='search' class='btn btn-sm btn-outline-info'>
                                </form>
                            </li>
                            <li class="list-group-item list-group-item-light">
                                Fame rating
                                <form action="{{ url_for('main.search_fame') }}" method="POST">
                                    <select class="form-control" name="fame" id="fame1">
                                        <option value="">Choose option</option>
                                        <option value="10">0% to 9%</option>
                                        <option value="20">10% to 19%</option>
                                        <option value="30">20% to 29%</option>
                                        <option value="40">30% to 39%</option>
                                        <option value="50">40% to 49%</option>
                                        <option value="60">50% to 59%</option>
                                        <option value="70">60% to 69%</option>
                                        <option value="80">70% to 79%</option>
                                        <option value="90">80% to 89%</option>
                                        <option value="100">90% to 100%</option>
                                    </select>
                                    <br />
                                    <input type="submit" name='submit' value='search' class='btn btn-sm btn-outline-info'>
                                </form>
                            </li>
                            <li class="list-group-item list-group-item-light">
                                Location
                                <form action="{{ url_for('main.search_location') }}" method="POST">
                                    <select class="form-control" name="location" id="location">
                                        <option value="">Choose option</option>
                                        <option value="Johannesburg">Johannesburg</option>
                                        <option value="Cape Town">Cape Town</option>
                                        <option value="Durban">Durban</option>
                                        <option value="Pretoria">Pretoria</option>
                                        <option value="Polokwane">Polokwane</option>
                                    </select>
                                    <br />
                                    <input type="submit" name='submit' value='search' class='btn btn-sm btn-outline-info'>
                                </form>
                            </li>
                            <li class="list-group-item list-group-item-light">
                                Interests
                                <form action="{{ url_for('main.search_interest') }}" method='POST'>
                                    <div class="form-group" id="test">
                                        <input type="checkbox" id="traveling" name="Traveling" value="Traveling">#Traveling<br>
                                        <input type="checkbox" id="animals" name="Animals" value="Animals">#Animals<br>
                                        <input type="checkbox" id="technology" name="Technology" value="Technology">#Technology<br>
                                        <input type="checkbox" id="sky-diving" name="Sky-diving" value="Sky-diving">#Sky-diving<br>
                                        <input type="checkbox" id="movies" name="Movies" value="Movies">#Movies<br>
                                        <input type="checkbox" id="music" name="Music" value="Music">#Music<br>
                                        <input type="checkbox" id="cooking" name="Cooking" value="Cooking">#Cooking<br>
                                        <input type="checkbox" id="sports" name="Sports" value="Sports">#Sports<br>
                                        <input type="checkbox" id="gaming" name="Gaming" value="Gaming">#Gaming<br>
                                    </div>
                                    <input type="submit" name='submit' value='search' class='btn btn-sm btn-outline-info'>
                                </form>
                            </li>
                            <!-- <li class="list-group-item list-group-item-light">
                                Advance Search
                                <br />
                                <input type="submit" name="submit" value="search" id="advance_search" onclick="advance_search()" class='btn btn-sm btn-outline-info'>
                            </li> -->
                        </ul>
                        <br />
                    </p>
                    {% else %}

                    {% endif %}
                </div>
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.1.1/socket.io.js"></script>
    {% block js %}{% endblock js %}
</body>

</html>

flask/matcha/templates/home.html
{% extends 'base.html' %} {% block content %}
<div class="bg-image"></div>

<div class="bg-text">
  <h1 style="font-size: 150px solid"><strong>Welcome to Matcha &#128525</strong></h1>
  <p style="font-style: italic;">"Sometimes we meet someone and feel like we have known them all our lives".</p>
</div>
  <br />
</div>
<div class="content-sections">
  {% for post in posts %}
  <article class="media content-section">
    <img
      class="article-img rounded"
      src="{{ url_for('static', filename='profile_pics/' + post['author']['image_name']) }}"
      alt="Profile Pic"
    />
    <div class="media-body">
      <div class="article-metadata border-bottom">
        <a
          class="mr-2"
          href="{{ url_for('profile.view_profile', user_id=post['author']['_id'])}}"
          >{{ post['author']['username'] }}</a
        >
        <small class="text-muted"
          >{{ post['date_posted'].strftime("%Y-%m-%d") }}</small
        >
      </div>
      <h2>
        <a
          class="article-title"
          href="{{ url_for('posts.post', post_id=post['_id'])}}"
          >{{ post['title'] }}</a
        >
      </h2>
      <p class="article-content">{{ post['content'] }}</p>
    </div>
  </article>
  {% endfor %}
</div>
{% endblock content %} {% block js %}
<script>
  socket = io.connect("http://localhost:5000");
  user_name = $("#username").text();

  socket.on("flirt", function (data) {
    $("notification").append(
      "<p>" + data["from"] + " has flirted with you</p>"
    );
    $("#badge").text("new");
  });

  socket.on("matched", function () {
    alert(data["from"] + " and you can now chat");
    $("notification").append(
      "<p> you and " + data["from"] + " can now chat.</p>"
    );
    $("#badge").text("new");
  });

  socket.on("notif_chat", function (data) {
    $("notification").append("<p>" + data["from"] + " sent you a message</p>");
    $("#badge").text("new");
  });

  socket.on("notif_view", function (data) {
    $("#notification").append(
      "<p>" + data["from"] + " viewed your profile</p>"
    );
    $("#badge").text("new");
  });

  socket.on("Unlike", function (data) {
    alert(data["from"] + " has unliked, so sad");
    window.location.reload();
  });

  $("#inbox").on("click", function () {
    socket.emit("read", { user: $("#username").text() });
    $("#badge").text("");
  });
</script>
{% endblock js %}